# Generated by Django 3.2.8 on 2023-02-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('close_box', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='close_box',
            name='payment_form',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
