# Generated by Django 3.2.8 on 2023-02-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('close_box', '0002_close_box_payment_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='close_box',
            name='cred',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='close_box',
            name='efec',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='close_box',
            name='trans',
            field=models.FloatField(default=0),
        ),
    ]
