# Generated by Django 3.2.8 on 2023-02-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20230211_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='metro_static',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='und_static',
            field=models.IntegerField(default=0),
        ),
    ]
