# Generated by Django 3.2.8 on 2023-02-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_invoice_pos_type_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_pos',
            name='anulated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice_pos',
            name='code',
            field=models.CharField(max_length=150),
        ),
    ]
