# Generated by Django 3.2.8 on 2023-02-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_auto_20230219_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet_pos',
            name='abono',
            field=models.FloatField(default=0),
        ),
    ]
