# Generated by Django 3.2.8 on 2023-02-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20230121_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='fe',
            field=models.BooleanField(default=False),
        ),
    ]
