# Generated by Django 3.2.8 on 2023-02-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_fe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolution_fe',
            name='from_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resolution_fe',
            name='resolution',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resolution_fe',
            name='to_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resolution_pos',
            name='from_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resolution_pos',
            name='resolution',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resolution_pos',
            name='to_number',
            field=models.IntegerField(default=0),
        ),
    ]
