# Generated by Django 3.2.8 on 2023-02-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_auto_20230118_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_fe',
            name='type_sell',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
