# Generated by Django 3.2.8 on 2023-02-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_invoice_fe_type_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_fe',
            name='anulated',
            field=models.BooleanField(default=False),
        ),
    ]
